lang = "en"

title = "Example.com"
subtitle = "An example blog"

# Used in the <title>
short_subtitle = "An example blog"

# Used in the meta description
description = "A longer description of this site"

copyright_years = "2022-2023"

# Used for the canonical url and other things
url = "https://example.com"

[localizedDate]
year = 'numeric'
month = 'short'
day = 'numeric'

[author]
nickname = "John"
fullname = "John Doe"

[[nav_links]]
label = "About"
url = "/about/"

[[nav_links]]
label = "Twitter"
url = "https://twitter.com/"
